"""Structural and provenance checks for the Homebrew Cask tap definition.

The cask at ``homebrew-tap/Casks/mefinder.rb`` is generated by
``scripts/update_homebrew_tap.py`` from built release artifacts. These tests
pin the committed definition to the digests of the published GitHub Release
assets and to the renderer output, so neither can drift silently.
"""

from __future__ import annotations

import hashlib
import importlib.util
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CASK_PATH = REPO_ROOT / "homebrew-tap" / "Casks" / "mefinder.rb"
SCRIPT_PATH = REPO_ROOT / "scripts" / "update_homebrew_tap.py"

# SHA-256 of the DMG assets published on GitHub Releases, cross-checked against
# the GitHub API and the local release/ artifacts. When the cask is updated to
# a new release, add its published digests here in the same change.
PUBLISHED_DMG_SHA256 = {
    "0.5.3": {
        "arm": "b9773adcd3683176b6ac9205e3c1a24629809665a6156238d2638ed748782fdc",
        "intel": "de058f8ffb4c8bb5dd79653b4b1e7d690fcb941c553746a3dae986cd89ba9a3b",
    },
}

HEX64_RE = re.compile(r"([0-9a-f]{64})")
VERSION_RE = re.compile(r'^  version "(\d+\.\d+\.\d+)"$', re.MULTILINE)


def load_script_module():
    """Import ``scripts/update_homebrew_tap.py`` as a module."""
    spec = importlib.util.spec_from_file_location("update_homebrew_tap", SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class HomebrewCaskDefinitionTests(unittest.TestCase):
    """The committed cask must match the published release it points at."""

    @classmethod
    def setUpClass(cls):
        cls.cask = CASK_PATH.read_text(encoding="utf-8")
        versions = VERSION_RE.findall(cls.cask)
        assert len(versions) == 1, versions
        cls.version = versions[0]

    def test_cask_is_tracked_in_git(self):
        result = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "ls-files", "--error-unmatch", "homebrew-tap/Casks/mefinder.rb"],
            capture_output=True,
        )
        self.assertEqual(result.returncode, 0, "tap cask must be committed, not ignored")

    def test_cask_token(self):
        self.assertTrue(self.cask.startswith('cask "mefinder" do\n'))

    def test_cask_version_is_a_published_release(self):
        self.assertIn(
            self.version,
            PUBLISHED_DMG_SHA256,
            "cask version has no published-digest baseline; "
            "update PUBLISHED_DMG_SHA256 together with the cask",
        )

    def test_cask_sha256_matches_published_digests(self):
        digests = HEX64_RE.findall(self.cask)
        baseline = PUBLISHED_DMG_SHA256[self.version]
        self.assertEqual(len(digests), len(baseline), digests)
        self.assertEqual(digests[0], baseline["arm"])
        self.assertEqual(digests[1], baseline["intel"])

    def test_cask_url_points_at_github_release_download(self):
        self.assertIn(
            "https://github.com/sabercomo/MEFinder/releases/download/"
            'v#{version}/MEFinder-v#{version}-macos-#{arch}.dmg',
            self.cask,
        )

    def test_cask_livecheck_tracks_github_latest(self):
        self.assertIn("https://github.com/sabercomo/MEFinder/releases/latest", self.cask)
        self.assertIn("strategy :github_latest", self.cask)

    def test_cask_installs_app_bundle(self):
        self.assertIn('  app "MEFinder.app"', self.cask)

    def test_cask_declares_macos_dependency(self):
        self.assertIn('  depends_on macos: :sonoma', self.cask)

    def test_cask_has_no_zap_so_user_data_is_preserved(self):
        self.assertNotIn("zap", self.cask)

    def test_cask_ruby_syntax(self):
        if shutil.which("ruby") is None:
            self.skipTest("ruby not available")
        result = subprocess.run(
            ["ruby", "-c", str(CASK_PATH)], capture_output=True, text=True
        )
        self.assertEqual(result.returncode, 0, result.stderr)


class UpdateHomebrewTapScriptTests(unittest.TestCase):
    """Unit tests for the cask renderer helpers."""

    @classmethod
    def setUpClass(cls):
        cls.script = load_script_module()

    def test_committed_cask_equals_rendered_output(self):
        baseline = PUBLISHED_DMG_SHA256[self._published_version()]
        rendered = self.script.render_cask(
            self._published_version(),
            {"arm64": baseline["arm"], "x86_64": baseline["intel"]},
            "sabercomo/MEFinder",
        )
        self.assertEqual(rendered, CASK_PATH.read_text(encoding="utf-8"))

    def _published_version(self) -> str:
        return max(PUBLISHED_DMG_SHA256, key=self.script.version_sort_key)

    def test_repo_slug_from_remote_urls(self):
        extract = self.script.repo_slug_from_remote_url
        self.assertEqual(extract("https://github.com/sabercomo/MEFinder.git"), "sabercomo/MEFinder")
        self.assertEqual(extract("git@github.com:sabercomo/MEFinder.git"), "sabercomo/MEFinder")
        self.assertEqual(extract("https://github.com/sabercomo/MEFinder"), "sabercomo/MEFinder")

    def test_parse_dmg_name(self):
        self.assertEqual(
            self.script.parse_dmg_name("MEFinder-v0.5.3-macos-arm64.dmg"),
            ("0.5.3", "arm64"),
        )
        with self.assertRaises(ValueError):
            self.script.parse_dmg_name("MEFinder-v0.5.3-macos-arm64.zip")

    def test_version_sort_key(self):
        self.assertLess(
            self.script.version_sort_key("0.5.3"),
            self.script.version_sort_key("0.10.0"),
        )

    def test_sha256_file(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "artifact.bin"
            path.write_bytes(b"mefinder")
            self.assertEqual(
                self.script.sha256_file(path),
                hashlib.sha256(b"mefinder").hexdigest(),
            )

    def test_render_cask_arm_only_declares_arch_gate(self):
        rendered = self.script.render_cask(
            "0.5.4", {"arm64": "a" * 64}, "sabercomo/MEFinder"
        )
        self.assertIn('  sha256 "' + "a" * 64 + '"', rendered)
        self.assertIn("MEFinder-v#{version}-macos-arm64.dmg", rendered)
        self.assertIn("depends_on arch: :arm64", rendered)
        self.assertIn('depends_on macos: :sonoma', rendered)
        self.assertNotIn('arch arm: "arm64", intel: "x86_64"', rendered)

    def test_render_cask_dual_arch_uses_interpolation(self):
        rendered = self.script.render_cask(
            "0.5.3",
            {"arm64": "a" * 64, "x86_64": "b" * 64},
            "sabercomo/MEFinder",
        )
        self.assertIn('arch arm: "arm64", intel: "x86_64"', rendered)
        self.assertIn('sha256 arm:   "' + "a" * 64 + '",', rendered)
        self.assertIn('intel: "' + "b" * 64 + '"', rendered)
        self.assertIn("-macos-#{arch}.dmg", rendered)
        self.assertIn('depends_on macos: :sonoma', rendered)
        self.assertNotIn("depends_on arch", rendered)

    def test_render_cask_rejects_bad_input(self):
        with self.assertRaises(ValueError):
            self.script.render_cask("0.5.3", {}, "sabercomo/MEFinder")
        with self.assertRaises(ValueError):
            self.script.render_cask("0.5.3", {"ppc": "a" * 64}, "sabercomo/MEFinder")

    def test_collect_arch_digests_validates_sidecar(self):
        digest = hashlib.sha256(b"mefinder").hexdigest()
        with tempfile.TemporaryDirectory() as tmp:
            release_dir = Path(tmp)
            dmg = release_dir / "MEFinder-v9.9.9-macos-arm64.dmg"
            dmg.write_bytes(b"mefinder")
            dmg.with_name(dmg.name + ".sha256.txt").write_text(
                f"{digest}  {dmg.name}\n", encoding="utf-8"
            )
            self.assertEqual(
                self.script.collect_arch_digests(release_dir, "9.9.9"),
                {"arm64": digest},
            )
            zero_digest = "0" * 64
            dmg.with_name(dmg.name + ".sha256.txt").write_text(
                f"{zero_digest}  {dmg.name}\n", encoding="utf-8"
            )
            with self.assertRaises(ValueError):
                self.script.collect_arch_digests(release_dir, "9.9.9")


if __name__ == "__main__":
    unittest.main()
