"""Stable document-group API; SQLite implementation lives in persistence."""

from .persistence.document_group_store import (
    TITLE_MAX_LENGTH,
    DocumentGroupNotFound,
    add_group_member,
    combine_into_group,
    create_document_group,
    delete_document_group,
    document_group_for_source,
    ensure_document_group_schema,
    list_document_groups,
    move_members_into_group,
    read_document_group_snapshot,
    remove_group_member,
    rename_document_group,
    replace_document_group_snapshot,
    resolve_document_group_source_ids,
    restore_document_group_snapshot,
    set_document_group_base,
    set_member_version_label,
)

__all__ = [
    "TITLE_MAX_LENGTH",
    "DocumentGroupNotFound",
    "add_group_member",
    "combine_into_group",
    "create_document_group",
    "delete_document_group",
    "document_group_for_source",
    "ensure_document_group_schema",
    "list_document_groups",
    "move_members_into_group",
    "read_document_group_snapshot",
    "remove_group_member",
    "rename_document_group",
    "replace_document_group_snapshot",
    "resolve_document_group_source_ids",
    "restore_document_group_snapshot",
    "set_document_group_base",
    "set_member_version_label",
]
