"""Versioned public HTTP contracts for the desktop-local API."""

GET_API_ROUTES = frozenset(
    {
        "/api/bibliographic-metadata",
        "/api/calibration",
        "/api/calibration-library",
        "/api/components",
        "/api/data-location",
        "/api/document-groups",
        "/api/document/pages",
        "/api/text-alignments/targets",
        "/api/text-alignment/models",
        "/api/import-resumable",
        "/api/import-status",
        "/api/index-meta",
        "/api/general-model",
        "/api/library",
        "/api/library/document",
        "/api/local-ocr",
        "/api/macos-update",
        "/api/mineru-accounts",
        "/api/mineru-config",
        "/api/mineru-local/component",
        "/api/mineru-statistics",
        "/api/parser-statistics",
        "/api/preferences",
        "/api/scan-directories",
        "/api/sources",
        "/api/update/status",
        "/api/vision-providers",
    }
)

POST_API_ROUTES = frozenset(
    {
        "/api/auto-page-mapping/accept",
        "/api/auto-page-mapping/apply",
        "/api/auto-page-mapping/detect",
        "/api/backup/export",
        "/api/backup/import",
        "/api/backup/import/choose",
        "/api/bibliographic-metadata/batch-detect",
        "/api/bibliographic-metadata/cnki-candidate",
        "/api/bibliographic-metadata/detect",
        "/api/bibliographic-metadata/lookup-cnki",
        "/api/bibliographic-metadata/lookup-crossref",
        "/api/bibliographic-metadata/lookup-google-books",
        "/api/bibliographic-metadata/open-cnki",
        "/api/bibliographic-metadata/parse-cnki-citation",
        "/api/bibliographic-metadata/save",
        "/api/calibration",
        "/api/data-location/choose",
        "/api/data-location/migrate",
        "/api/document-groups/add-member",
        "/api/document-groups/combine",
        "/api/document-groups/create",
        "/api/document-groups/delete",
        "/api/document-groups/remove-member",
        "/api/document-groups/rename",
        "/api/document-groups/set-base",
        "/api/document-groups/version-label",
        "/api/document/citation",
        "/api/text-alignments/generate",
        "/api/text-alignments/locate",
        "/api/text-alignment/models",
        "/api/document/export",
        "/api/document/export-epub",
        "/api/document/export-markdown",
        "/api/documents/remove",
        "/api/documents/remove-batch",
        "/api/export-directory/choose",
        "/api/import",
        "/api/import-local",
        "/api/import-resume",
        "/api/import-resume-dismiss",
        "/api/import-retry",
        "/api/import-retry-mineru",
        "/api/import-retry-mineru-local",
        "/api/import-upload/cancel",
        "/api/import-upload/chunk",
        "/api/import-upload/finish",
        "/api/import-upload/start",
        "/api/general-model",
        "/api/general-model/models",
        "/api/general-model/test",
        "/api/local-ocr",
        "/api/local-ocr/component",
        "/api/local-ocr/test",
        "/api/mineru-accounts",
        "/api/mineru-accounts/service",
        "/api/mineru-accounts/test",
        "/api/mineru-config",
        "/api/mineru-config/test",
        "/api/mineru-local",
        "/api/mineru-local/component",
        "/api/mineru-local/test",
        "/api/mineru-reparse",
        "/api/open-mineru-token",
        "/api/open-source",
        "/api/preferences",
        "/api/scan-directories/choose",
        "/api/search",
        "/api/update/check",
        "/api/update/download",
        "/api/update/install",
        "/api/vision-providers",
        "/api/vision-providers/models",
        "/api/vision-providers/test",
    }
)


# Only state-changing interfaces where a request/response drift can corrupt or
# strand user data are modeled here. Route presence remains frozen above; this
# table deliberately does not attempt to model every desktop-local endpoint.
HIGH_RISK_WRITE_CONTRACTS = {
    "/api/import-upload/start": {
        "request": {
            "required": {"file_name": "string", "size": "integer"},
            "optional": {
                "parse_mode": "string",
                "provider_id": "string",
                "import_kind": "string",
            },
        },
        "success": {
            "status": [200],
            "required": {
                "ok": "boolean",
                "upload_id": "string",
                "chunk_size": "integer",
                "total_size": "integer",
                "file_name": "string",
            },
        },
    },
    "/api/import-upload/finish": {
        "request": {"required": {"upload_id": "string"}, "optional": {}},
        "success": {
            "status": [200],
            "required": {
                "ok": "boolean",
                "job_id": "string",
                "file_name": "string",
                "source_file_id": "string",
                "detected_pdf_type": "string|null",
                "parse_route": "string|null",
                "provider_id": "string|null",
            },
        },
    },
    "/api/import-retry": {
        "request": {
            "required": {"job_id": "string", "provider_id": "string"},
            "optional": {},
        },
        "success": {
            "status": [200],
            "required": {
                "ok": "boolean",
                "job_id": "string",
                "provider_id": "string",
                "provider_name": "string",
                "parse_route": "string",
            },
        },
    },
    "/api/import-resume": {
        "request": {"required": {"job_id": "string"}, "optional": {}},
        "success": {
            "status": [200],
            "required": {
                "ok": "boolean",
                "job_id": "string",
                "parse_route": "string|null",
                "provider_id": "string|null",
                "provider_name": "string|null",
            },
        },
    },
    "/api/mineru-accounts/service": {
        "request": {"required": {"api_base": "string"}, "optional": {}},
        "success": {
            "status": [200],
            "required": {
                "configured": "boolean",
                "api_base": "string",
                "accounts": "array",
                "statistics": "object",
                "local_deployment": "object",
            },
        },
    },
    "/api/vision-providers": {
        "request": {
            "required": {"action": "string"},
            "optional": {
                "provider": "object",
                "provider_id": "string",
                "auto_fallback_from_mineru": "boolean",
            },
        },
        "success": {
            "status": [200],
            "required": {
                "ok": "boolean",
                "providers": "array",
                "default_provider_id": "string|null",
                "auto_fallback_from_mineru": "boolean",
                "has_configured_provider": "boolean",
            },
        },
    },
    "/api/data-location/migrate": {
        "request": {"required": {"target_path": "string"}, "optional": {}},
        "success": {
            "status": [200],
            "required": {
                "ok": "boolean",
                "current_path": "string",
                "target_path": "string",
                "restart_required": "boolean",
                "old_data_retained": "boolean",
                "message": "string",
            },
        },
    },
}
